name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.dev -t test .

      - name: Run tests
        run: |
          docker run --rm -e CI=true test npm run test
